resources:
  - name: mariadbtestRepo
    type: GitRepo
    configuration:
      gitProvider: PradnyaGithub               # Change to your integration
      path: pradsjfrog/pipelines_helloworld                 # Change to your repo
      branches: 
        include: ^dockertest$
  - name: mariadbinit
    type: Image
    configuration:
      sourceRepository: docker-remote
      registry: ArtifactoryIntegration
      imageName: 34.77.95.84:8082/docker-remote/mariadb
      imageTag: 10.2.23
      autoPull: false #default 
      
pipelines:
  - name: pipeline_mariadbtest
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello Pipelines 3!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: mariadbtestRepo
            - name: mariadbinit
          integrations:
            - name: ArtifactoryIntegration
        execution:
          onExecute:
            - wget -nv https://api.bintray.com/content/jfrog/jfrog-cli-go/1.35.3/jfrog-cli-linux-amd64/jfrog?bt_package=jfrog-cli-linux-amd64 -O jfrog --no-check-certificate
            - sudo chmod +x jfrog
            - mv jfrog /usr/bin/jfrog
            # - jfrog rt docker-pull 34.77.95.84:8082/docker-remote/mariadb:10.2.23 docker-remote
            - jfrog --version
            - jfrog rt docker-pull 34.77.95.84:8082/docker-remote/mariadb:10.2.23 docker-remote --build-name=pipeline_mariadbtest --build-number=1
            #- docker images  
