resources:
  - name: mariadbtestRepo
    type: GitRepo
    configuration:
      gitProvider: PradnyaGithub               # Change to your integration
      path: pradsjfrog/pipelines_helloworld                 # Change to your repo
      branches: 
        include: ^dockertest$
  - name: mariadbinit
    type: Image
    configuration:
      sourceRepository: docker-remote
      registry: ArtifactoryIntegration
      imageName: 34.77.95.84:8082/docker-remote/mariadb
      imageTag: 10.2.23
      autoPull: true #default
      
pipelines:
  - name: pipeline_mariadbtest
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello Pipelines 3!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
            - name: mariadbinit
          integrations:
            - name: ArtifactoryIntegration
        execution:
          onExecute:
            # jfrog rt docker-pull 34.77.95.84:8082/docker-remote/mariadb:10.2.23 docker-remote
